version: "3"

services:
    timeseries-etl:
        container_name: ts-etl-prod
        build:
            context: ../../
            dockerfile: ./docker/prod/Dockerfile
            target: prod
        volumes:
            - ../../data:/app/data
            - ../../logs:/app/logs
        command: bash -c "python /app/src/run.py"

